# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66ec54c7595fd871f7f4c2aecc2d5f5a56d1edec58c0300c3bf95da2fa3c4bd5c631640d3015fba7957261eb25cdd2f47fbd6b860bd3c28ddc9d1573fe242a71

test:
  secret_key_base: 7457c4c29569bb5f96e10645f07ee762e0cf4d13c437667eab7c1b90420df84db4d42479ae419acddc7c4fe4ee14675c7ef236c7b855c2e5fff4114aec9f40ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
