# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d253fecb63adef771c760ecc868cca9821f88c8b068ecdd908c819fae06a2b640b69d54e0a2953215fb8c50917aabbb9f26c83ed2496ab7e1a99abf8a1abeb17

test:
  secret_key_base: a655f903b45cfd4d3dd12929f1a588fb9dee94daf6ff0c31bdc6ef2e2c89cb428834b1d0f3b339001851f0e3cdd6d351d14a73257feb598c130f7075e967997e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
