# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e97f144882b2282413f949312f954eadc4187fefe06bfc55254fd377b4c35690b518eac688e2d47192b85944a5ccb80ecb33f54bfb081977553db6a373ad457

test:
  secret_key_base: 3f77b9b55862de7589f6216d47af4b5dc58efd8c8e6fc64074a7d46b3cad325b67697e90822d860d227e64608fd1fc8734f8f6d5a8e794a808bef71ec3e7411e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
