# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ac964466c64263af4c7cb97c99011ec6de4b28c16d23fd61d1bbbe994167f5404afa029ce0cfdbdc4686a0b8932b3b1e05b213bd24bbde1023811adc24de518

test:
  secret_key_base: a032a149df576a091da67fb8a6767f9538a9259388b0db6896ea96910f56254780338eb9b4fc145aacd23c53238d1b507c2d6971e94a9db87c546b57a02bcd15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
