# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-23 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20180123_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='HELLO!'),
        ),
    ]
