# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24036ae9bd40465852517bc38c9af2818d0cdcf3528e9dd3eaf6f0df414e7bb13fc7d010bfc85418aef87bc0ccd8e0b5c456a7017b434c7f3c6a6bfbad199f04

test:
  secret_key_base: 18173a43f3d72fcb9adcfd13edb64f735751ef8fd356a2e47bc66512af16a2d3631e3110577a0529834efa9773bdb5d4e019d03b1a278c1596f8d87edc8ac8bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
